spring.application.name=auth-service
server.port=8081

eureka.client.serviceUrl.defaultZone=http://localhost:8763/eureka
spring.cloud.compatibility-verifier.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.private-key=${JWT_PRIVATE_SECRET}
jwt.public-key=${JWT_PUBLIC_SECRET}
jwt.secret=${JWT_SECRET}
jwt.expiration=900000